### ISSUE TITLE
Any kind of license on these?

### ISSUE THREAD

**Issue by kostasx** [MaggieAppleton/react-metaphors-slides#1]
These are excellent, and I was wondering whether one could use them in their slides or class notes, accompanied of course, with the appropriate mention.

Thank you so much!

**Comment by MaggieAppleton** [comment]
Oh good point! Thanks for reminding me to add one - just popped the [CC Attribution-ShareAlike](https://creativecommons.org/licenses/by-sa/4.0/) one on.
